In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])
b = np.array([[22, 34, 16], [4, 9, 10]])

In [ ]:
print(a)
print(b)

[1 2 3]
[[22 34 16]
 [ 4  9 10]]


In [ ]:
z = np.zeros((3,4))
o = np.ones((3,4))
r = np.random.rand(3,4)
i = np.eye(3) # identity

print(z)
print(o)
print(r)
print(i)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0.88921182 0.07946127 0.52703022 0.4417529 ]
 [0.1732114  0.84865241 0.29235525 0.44320864]
 [0.83049077 0.825116   0.31688709 0.97687314]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# attribute / properties
print(a.shape)
print(b.shape)
print(a.ndim)
print(b.ndim)
print(a.size)
print(b.size)
print(a.dtype)
print(b.dtype)


(3,)
(2, 3)
1
2
3
6
int64
int64


In [ ]:
# slicing & indexing

nums = [12, 33, 44, 17, 46, 18, 12]

print(nums[3]) # 17
print(nums[-1]) # 12
print(nums[-2]) # 18

print(nums[2:5])

print(b[1,1])
print(b[1,:])
print(b[:,1])

17
12
18
[44, 17, 46]
9
[ 4  9 10]
[34  9]


In [ ]:
x = np.array([4, 5, 9])
y = np.array([1, 2, 4])

sum = x + y
print(sum)

mult = x * y
print(mult)

sq = x**2
print(sq)

print(x + 11)


[ 5  7 13]
[ 4 10 36]
[16 25 81]
[15 16 20]


In [ ]:
print(np.vstack([x,y]))
print(np.hstack([x,y]))

[[4 5 9]
 [1 2 4]]
[4 5 9 1 2 4]


In [ ]:
mat1 = np.hstack([x,y])

print(np.mean(mat1))
print(np.median(mat1))
print(np.std(mat1))
print(np.min(mat1))
print(np.max(mat1))

4.166666666666667
4.0
2.5440562537456244
1
9


In [ ]:
print(b)
print(b.flatten())

[[22 34 16]
 [ 4  9 10]]
[22 34 16  4  9 10]


In [ ]:
mat = np.arange(16).reshape(4,4)
print(mat)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
